Align segment structure with openai/whisper
guillaumekln/faster-whisper pull request #154
Opened 2023-04-16 01:55 UTC by tekacs

At the moment, the segments returned by faster-whisper are a subtly different shape to those returned by Whisper and also lack some of the information that JSON/verbose transcription results from that repo provide.

It appears that all of the information necessary to return these is in fact present in the transcribe function of faster-whisper, but they're simply not returned at present.

This PR adds those in and adjusts the naming of avg_log_prob to be consistent with Whisper.

The quirk I'm not certain of is whether it would be best to adjust the returned `seek` value on the other side of the VAD, but I don't do that at present.

2023-04-16 02:53 UTC, palladium123 commented
I created a PR for this in the past (before VAD was implemented), but I only implemented avg_logprob (sorry @guillaumekln  typo there in my original PR) and no_speech_prob as I at that time I didn't think the other values will change things from a decision making perspective (whether to reject the output or not, or to assess the reliability of the output). In hindsight, I could see how knowing the temperature of the output can be useful (as temperature >0 may not be reliable). 

I do wonder if VAD actually makes no_speech_prob (kinda) obsolete.....

2023-04-16 08:54 UTC, guillaumekln requested changes
Thanks! It makes sense to match the openai/whisper format even though I think some attributes are not very useful (especially `id` which is trivial to compute).

Regarding `seek` I don't think it is necessary to adjust it based on VAD. It will just make things more complex.

2023-04-16 08:54 UTC, guillaumekln commented on faster_whisper/transcribe.py
> +                    id=idx,
The id goes back to 0 when moving to the next 30-second window. You should increment a global index instead.

2023-04-16 08:54 UTC, guillaumekln commented on faster_whisper/transcribe.py
>              cum_log_prob = result.scores[0] * (seq_len**options.length_penalty)
Can you rename `cum_log_prob` to `cum_logprob` for consistency with `avg_logprob`?

2023-04-24 13:04 UTC, guillaumekln approved these changes

2023-04-24 13:04 UTC, merged